name: Test Cron Action

on:
  schedule:
    # Se ejecuta estrictamente cada 3 minutos
    - cron: '*/3 * * * *'
  workflow_dispatch: # Te permite darle clic a "Run workflow" manualmente para probarlo al instante

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "¡Hola! La Action está corriendo correctamente a las $(date)"
          echo "El sistema de GitHub Actions está respondiendo al cronómetro de 3 minutos."
